### ISSUE TITLE
Rick - storage in the cluster

### ISSUE THREAD

**Issue by tumido** [operate-first/hetzner-baremetal-openshift#14]
Related: #12 

Figure out how to approach storage in Hetzner, where we don't have access to dedicated storage data lake like in MOC. 

@rbo, @larsks had some ideas how to solve the storage provisioning in-cluster for the Rick cluster, without OCS and possibly with less overhead, let's discuss here.

**Comment by larsks** [comment]
You have a couple of options for consuming local disk as PV storage.

If you install the `local-storage` operator, you can expose local block devices as PVs. This is fine if you only need one or two, but because it doesn't support dynamic provisioning it's not terribly useful for anything more than that (you can use LVM to split up a single large disk into multiple smaller PVs).

If you install the CNV operator, as part of the bundle you get the [HostPath Provisioner][hpp], which lets you dynamically provision PVs from a specific path on your host. This means you can create PersistentVolumeClaims and the provisioner will allocate a PV automatically.

The other downside may be that you need entitlements for CNV just to make use of the HostPath provisioner.

The downside to the HostPath Provisioner is, of course, that storage is bound to specific nodes: a pod using a PV can't be relocated to another node.

[hpp]: https://docs.openshift.com/container-platform/4.7/virt/virtual_machines/virtual_disks/virt-configuring-local-storage-for-vms.html

**Comment by rbo** [comment]
To use local storage with HostPath Provisioner is well known to me and perfect for VM's to have good performance because of local storage and of course you lose VM migration feature. Lost the node, lost the VM...  

For some kind of pods, it would be also fine to use local storage. But for example for the local image registry, this is not an option.  The Hetzner servers are cheap servers, it cloud happen that we lose a node because of hardware failure. In case the registry & storage is located on that particular node we lose all container images stored in the image registry.

For now, we have only 3 worker nodes with 2x 480 GB SSD ([details](https://github.com/operate-first/hetzner-baremetal-openshift/issues/6#issuecomment-866205831)) first one is used for RHCOS and the second one planed for OCS/ODF ~ 3x480 GB is not that much storage at all.

**Comment by rbo** [comment]
I installed OCS/ODF at the Rick cluster. 
OCS/ODF requirements: 
 * 30 CPU (logical)
 * 72 GiB memory

Available in the cluster:
* 60 CPU's
* 943 GiB memory 

Let's give it a try with OCS/ODF. 

Application/User Workload should be only allowed with quotas! 

I'm very interested if this kind of setup works very well, and what we have to take care of.

**Comment by rbo** [comment]
With installation, the storage question is solved for now.
